### ISSUE TITLE
cleanMsChar() method should be static?

### ISSUE THREAD

**Issue by kevinwojo** [hubzero/framework#103]
https://github.com/hubzero/framework/blob/master/src/Utility/Sanitize.php#L243

All the other methods are public static methods, should cleanMsChar() be allowed to be called statically? It's not obvious to me why it shouldn't be.

**Comment by spwilson806** [comment]
I would say yes.  I see no references to the method in the CMS.  And given the context of the class (everything else is static), I'd say this should be static as well.

**Comment by zooley** [comment]
Agreed. That method was originally apart of com_resources, if memory serves. An attempt to deal with people pasting in content from MS Word.
